services:
  nestjs-boilerplate-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      DATABASE_URL: ${DATABASE_URL:-}
    image: nestjs-boilerplate-backend:latest
    container_name: nestjs-boilerplate-backend
    restart: always
    ports:
      - "${APP_HOST_PORT:-3000}:${APP_DOCKER_PORT:-3000}"
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
    depends_on:
      - nestjs-boilerplate-db

  nestjs-boilerplate-db:
    image: postgres:17.2
    container_name: nestjs-boilerplate-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-nestjs-boilerplate}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nestjs-boilerplate}
      POSTGRES_DB: ${POSTGRES_DB:-nestjs-boilerplate}
    volumes:
      - nestjs-boilerplate-data-prod:/var/lib/postgresql/data

volumes:
  nestjs-boilerplate-data-prod:
