services:
  nestjs-boilerplate-db:
    ports:
      - "${DATABASE_HOST_PORT:-5432}:${DATABASE_DOCKER_PORT:-5432}"
    volumes:
      - nestjs-boilerplate-data-dev:/var/lib/postgresql/data

volumes:
  nestjs-boilerplate-data-dev:
