services:
  dictionary-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      DATABASE_URL: ${DATABASE_URL:-}
    image: dictionary-backend:latest
    container_name: dictionary-backend
    restart: always
    ports:
      - "${APP_HOST_PORT:-3000}:${APP_DOCKER_PORT:-3000}"
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
    depends_on:
      - postgres

  postgres:
    image: postgres:17.2
    container_name: dictionary-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-dictionary}
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data

volumes:
  postgres-data-prod:
